import './globals.css';
import {headers} from 'next/headers';
import LanguageNav from '../components/LanguageNav';

export const dynamic='force-dynamic';
export const metadata={title:{default:'EnteleBANK | A TVK Group Company',template:'%s | EnteleBANK'},description:'EnteleBANK is a proposed UK digital banking institution under development.',metadataBase:new URL('https://www.entelebank.com'),alternates:{canonical:'/'},icons:{icon:'/brand/entelebank-mark.svg',shortcut:'/brand/entelebank-mark.svg'},openGraph:{title:'EnteleBANK | A TVK Group Company',description:'A proposed UK digital banking institution under development.',url:'https://www.entelebank.com',siteName:'EnteleBANK',type:'website'}};
function Brand({footer=false}){return <a className={`brandLogo${footer?' footerBrand':''}`} href="/" aria-label="EnteleBANK home"><img src="/brand/entelebank-wordmark.svg" alt="EnteleBANK — A TVK Group Company"/></a>}
async function pathName(){const h=await headers();return h.get('x-next-url')||h.get('x-invoke-path')||h.get('x-matched-path')||''}
export default async function RootLayout({children}){const path=await pathName();const localized=/^\/(de|tr|fr|es|it|pt|nl|pl|uk|ru|ro|bg|el|cs|sk|hu|ar|fa|he|zh|ja|ko|hi|id)(\/|$)/.test(path);return <html lang="en"><body>{localized?children:<><a className="skipLink" href="#main-content">Skip to main content</a><div className="status">PROPOSED UK BANKING INSTITUTION · PRE-AUTHORISATION</div><header><Brand/><div className="headerActions"><nav aria-label="Primary navigation"><a href="/about">About</a><a href="/personal">Personal</a><a href="/business">Business</a><a href="/infrastructure">Infrastructure</a><a href="/security">Security</a><a href="/governance">Governance</a><a href="/roadmap">Roadmap</a><a href="/regulatory">Regulatory</a></nav><LanguageNav/></div></header><div id="main-content">{children}</div><footer><Brand footer/><div><p>EnteleBANK is under development and is not currently authorised by the PRA or FCA to accept deposits or provide regulated banking services.</p><p className="footerLinks"><a href="/about">About</a><a href="/personal">Personal</a><a href="/business">Business</a><a href="/infrastructure">Infrastructure</a><a href="/governance">Governance</a><a href="/roadmap">Roadmap</a><a href="/regulatory">Regulatory status</a><a href="/security">Security</a><a href="/privacy">Privacy</a><a href="/cookies">Cookies</a><a href="/terms">Terms</a></p></div><p>© 2026 EnteleBANK. All rights reserved.</p></footer></>}</body></html>}
