import {notFound} from 'next/navigation';
import LanguageMenu from '../../components/LanguageMenu';
import {isLocale} from '../../lib/i18n';
const shell={
tr:{banner:'ÖNERİLEN BİRLEŞİK KRALLIK BANKACILIK KURULUŞU · YETKİLENDİRME ÖNCESİ',nav:{about:'Hakkımızda',personal:'Bireysel',business:'Ticari',infrastructure:'Altyapı',security:'Güvenlik',governance:'Yönetişim',roadmap:'Yol haritası',regulatory:'Düzenleyici durum'},footerNotice:'EnteleBANK geliştirme aşamasındadır ve şu anda PRA veya FCA tarafından mevduat kabul etmek ya da düzenlemeye tabi bankacılık hizmetleri sunmak üzere yetkilendirilmiş değildir.',links:{privacy:'Gizlilik',cookies:'Çerezler',terms:'Koşullar'},copyright:'© 2026 EnteleBANK. Tüm hakları saklıdır.',skip:'Ana içeriğe geç',home:'EnteleBANK ana sayfa',navLabel:'Ana navigasyon',company:'Bir TVK Group Şirketi'},
de:{banner:'VORGESCHLAGENES UK-BANKINSTITUT · VOR DER ZULASSUNG',nav:{about:'Über uns',personal:'Privatkunden',business:'Firmenkunden',infrastructure:'Infrastruktur',security:'Sicherheit',governance:'Governance',roadmap:'Fahrplan',regulatory:'Regulatorischer Status'},footerNotice:'EnteleBANK befindet sich in Entwicklung und ist derzeit weder von PRA noch FCA zur Entgegennahme von Einlagen oder zur Erbringung regulierter Bankdienstleistungen zugelassen.',links:{privacy:'Datenschutz',cookies:'Cookies',terms:'Bedingungen'},copyright:'© 2026 EnteleBANK. Alle Rechte vorbehalten.',skip:'Zum Hauptinhalt springen',home:'EnteleBANK Startseite',navLabel:'Hauptnavigation',company:'Ein Unternehmen der TVK Group'},
fr:{banner:'PROJET D’ÉTABLISSEMENT BANCAIRE AU ROYAUME-UNI · AVANT AUTORISATION',nav:{about:'À propos',personal:'Particuliers',business:'Entreprises',infrastructure:'Infrastructure',security:'Sécurité',governance:'Gouvernance',roadmap:'Feuille de route',regulatory:'Statut réglementaire'},footerNotice:'EnteleBANK est en cours de développement et n’est actuellement pas autorisé par la PRA ou la FCA à accepter des dépôts ni à fournir des services bancaires réglementés.',links:{privacy:'Confidentialité',cookies:'Cookies',terms:'Conditions'},copyright:'© 2026 EnteleBANK. Tous droits réservés.',skip:'Aller au contenu principal',home:'Accueil EnteleBANK',navLabel:'Navigation principale',company:'Une société de TVK Group'},
es:{banner:'ENTIDAD BANCARIA PROPUESTA EN EL REINO UNIDO · PREVIA A LA AUTORIZACIÓN',nav:{about:'Acerca de',personal:'Particulares',business:'Empresas',infrastructure:'Infraestructura',security:'Seguridad',governance:'Gobernanza',roadmap:'Hoja de ruta',regulatory:'Situación regulatoria'},footerNotice:'EnteleBANK está en desarrollo y actualmente no está autorizado por la PRA ni por la FCA para aceptar depósitos o prestar servicios bancarios regulados.',links:{privacy:'Privacidad',cookies:'Cookies',terms:'Condiciones'},copyright:'© 2026 EnteleBANK. Todos los derechos reservados.',skip:'Ir al contenido principal',home:'Inicio de EnteleBANK',navLabel:'Navegación principal',company:'Una empresa de TVK Group'},
it:{banner:'ISTITUTO BANCARIO PROPOSTO NEL REGNO UNITO · PRE-AUTORIZZAZIONE',nav:{about:'Chi siamo',personal:'Privati',business:'Imprese',infrastructure:'Infrastruttura',security:'Sicurezza',governance:'Governance',roadmap:'Roadmap',regulatory:'Stato regolamentare'},footerNotice:'EnteleBANK è in fase di sviluppo e attualmente non è autorizzata dalla PRA o dalla FCA ad accettare depositi o fornire servizi bancari regolamentati.',links:{privacy:'Privacy',cookies:'Cookie',terms:'Condizioni'},copyright:'© 2026 EnteleBANK. Tutti i diritti riservati.',skip:'Vai al contenuto principale',home:'Home EnteleBANK',navLabel:'Navigazione principale',company:'Una società di TVK Group'}};
export default async function LocaleLayout({children,params}){const {locale}=await params;if(!isLocale(locale))notFound();const s=shell[locale];if(!s)return children;const p=`/${locale}`;return <div lang={locale}><a className="skipLink" href="#locale-main">{s.skip}</a><div className="status">{s.banner}</div><header><a className="brandLogo" href={p} aria-label={s.home}><img src="/brand/entelebank-wordmark.svg" alt={`EnteleBANK — ${s.company}`}/></a><div className="headerActions"><nav aria-label={s.navLabel}><a href={`${p}/about`}>{s.nav.about}</a><a href={`${p}/personal`}>{s.nav.personal}</a><a href={`${p}/business`}>{s.nav.business}</a><a href={`${p}/infrastructure`}>{s.nav.infrastructure}</a><a href={`${p}/security`}>{s.nav.security}</a><a href={`${p}/governance`}>{s.nav.governance}</a><a href={`${p}/roadmap`}>{s.nav.roadmap}</a><a href={`${p}/regulatory`}>{s.nav.regulatory}</a></nav><LanguageMenu current={locale}/></div></header><div id="locale-main">{children}</div><footer><a className="brandLogo footerBrand" href={p}><img src="/brand/entelebank-wordmark.svg" alt={`EnteleBANK — ${s.company}`}/></a><div><p>{s.footerNotice}</p><p className="footerLinks"><a href={`${p}/regulatory`}>{s.nav.regulatory}</a><a href={`${p}/security`}>{s.nav.security}</a><a href={`${p}/privacy`}>{s.links.privacy}</a><a href={`${p}/cookies`}>{s.links.cookies}</a><a href={`${p}/terms`}>{s.links.terms}</a></p></div><p>{s.copyright}</p></footer></div>}
